# Dockerfile

FROM debian:stretch
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apt-get -y update

RUN apt-get install -y --no-install-recommends openjdk-8-jdk maven

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH $JAVA_HOME/bin:$PATH

# build dependencies

RUN apt-get install -y --no-install-recommends git curl
RUN apt-get install -y --no-install-recommends build-essential pkg-config cmake libssl-dev libsqlite3-dev libsodium-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN cd /opt/ && git clone https://github.com/hyperledger/indy-sdk.git && cd indy-sdk && git checkout v1.3.0
RUN cd /opt/indy-sdk/libindy/ && ~/.cargo/bin/cargo clean && ~/.cargo/bin/cargo build
RUN cd /opt/indy-sdk/wrappers/java/ && mvn clean install -DskipTests

# build driver-did-sov

ADD . /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean
RUN cd /opt/uni-resolver-java && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/uni-resolver-core && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver-did-sov && mvn install package -N -DskipTests

RUN mkdir /opt/uni-resolver-java/driver-did-sov/lib/
RUN cp /opt/indy-sdk/libindy/target/debug/libindy.so /opt/uni-resolver-java/driver-did-sov/sovrin/lib/

# clean up

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# variables

ARG libIndyPath=./sovrin/lib/
ARG poolConfigName=11347-04
ARG poolGenesisTxn=./sovrin/11347-04.txn
ARG walletName=default

ENV uniresolver_driver_did_sov_libIndyPath $libIndyPath
ENV uniresolver_driver_did_sov_poolConfigName $poolConfigName
ENV uniresolver_driver_did_sov_poolGenesisTxn $poolGenesisTxn
ENV uniresolver_driver_did_sov_walletName $walletName

# done

EXPOSE 8080

CMD "/opt/uni-resolver-java/docker/run-driver-did-sov.sh"
