# Dockerfile

FROM debian:stretch
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apt-get -y update

RUN apt-get install -y --no-install-recommends openjdk-8-jdk maven

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH $JAVA_HOME/bin:$PATH

# build driver-did-erc725

ADD . /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean
RUN cd /opt/uni-resolver-java && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/uni-resolver-core && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver-did-erc725 && mvn install package -N -DskipTests

# clean up

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# variables

ENV uniresolver_driver_did_erc725_ethereumConnection jsonrpc
ENV uniresolver_driver_did_erc725_rpcUrlMainnet https://mainnet.infura.io/9W2fvWQMP6cJCMH3ESqP
ENV uniresolver_driver_did_erc725_rpcUrlRopsten https://ropsten.infura.io/9W2fvWQMP6cJCMH3ESqP
ENV uniresolver_driver_did_erc725_rpcUrlRinkeby https://rinkeby.infura.io/9W2fvWQMP6cJCMH3ESqP
ENV uniresolver_driver_did_erc725_rpcUrlKovan https://kovan.infura.io/9W2fvWQMP6cJCMH3ESqP
ENV uniresolver_driver_did_erc725_etherscanApiMainnet http://api.etherscan.io/api
ENV uniresolver_driver_did_erc725_etherscanApiRopsten http://api-ropsten.etherscan.io/api
ENV uniresolver_driver_did_erc725_etherscanApiRinkeby http://api-rinkeby.etherscan.io/api
ENV uniresolver_driver_did_erc725_etherscanApiKovan http://api-kovan.etherscan.io/api

# done

EXPOSE 8080

CMD "/opt/uni-resolver-java/docker/run-driver-did-erc725.sh"
