# Dockerfile

FROM debian:stretch
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apt-get -y update

RUN apt-get install -y --no-install-recommends openjdk-8-jdk maven

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH $JAVA_HOME/bin:$PATH

# build dependencies

RUN apt-get install -y --no-install-recommends git

RUN cd /opt/ && git clone https://github.com/peacekeeper/did-common-java.git
RUN cd /opt/did-common-java/ && mvn clean install -DskipTests

RUN apt-get install -y --no-install-recommends curl build-essential pkg-config cmake libssl-dev libsqlite3-dev libsodium-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN cd /opt/ && git clone https://github.com/hyperledger/indy-sdk.git && cd indy-sdk && git checkout v1.3.0
RUN cd /opt/indy-sdk/libindy/ && ~/.cargo/bin/cargo clean && ~/.cargo/bin/cargo build
RUN cd /opt/indy-sdk/wrappers/java/ && mvn clean install -DskipTests

# build driver-did-sov

ADD . /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean
RUN cd /opt/uni-resolver-java && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/uni-resolver-core && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver && mvn install -N -DskipTests
RUN cd /opt/uni-resolver-java/driver-did-sov && mvn install package -N -DskipTests

RUN mkdir /opt/uni-resolver-java/driver-did-sov/lib/
RUN cp /opt/indy-sdk/libindy/target/debug/libindy.so /opt/uni-resolver-java/driver-did-sov/sovrin/lib/

# clean up

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# variables

ENV uniresolver_driver_did_sov_libIndyPath ./sovrin/lib/
ENV uniresolver_driver_did_sov_poolConfigName 11347-04
ENV uniresolver_driver_did_sov_poolGenesisTxn ./sovrin/11347-04.txn
ENV uniresolver_driver_did_sov_walletName default

# done

EXPOSE 8080

CMD "/opt/uni-resolver-java/docker/run-driver-did-sov.sh"
