version: "3.5"
networks:
  default:
    name: universal-resolver
services:
  driver-did-btcr:
    image: universalresolver/driver-did-btcr:latest
    environment:
      uniresolver_driver_did_btcr_bitcoinConnection: ${uniresolver_driver_did_btcr_bitcoinConnection}
      uniresolver_driver_did_btcr_rpcUrlMainnet: ${uniresolver_driver_did_btcr_rpcUrlMainnet}
      uniresolver_driver_did_btcr_rpcUrlTestnet: ${uniresolver_driver_did_btcr_rpcUrlTestnet}
    ports:
      - "8081:8080"
  driver-did-sov:
    image: universalresolver/driver-did-sov:latest
    environment:
      uniresolver_driver_did_sov_libIndyPath: ${uniresolver_driver_did_sov_libIndyPath}
      uniresolver_driver_did_sov_poolConfigs: ${uniresolver_driver_did_sov_poolConfigs}
      uniresolver_driver_did_sov_poolVersions: ${uniresolver_driver_did_sov_poolVersions}
      uniresolver_driver_did_sov_walletName: ${uniresolver_driver_did_sov_walletName}
    ports:
      - "8082:8080"
  uni-resolver-driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:1.3.1
    ports:
      - "8083:8081"
  driver-did-stack:
    image: universalresolver/driver-did-stack:latest
    ports:
      - "8084:8080"
  driver-did-erc725:
    image: universalresolver/driver-did-erc725:latest
    environment:
      uniresolver_driver_did_erc725_ethereumConnections: ${uniresolver_driver_did_erc725_ethereumConnections}
      uniresolver_driver_did_erc725_rpcUrls: ${uniresolver_driver_did_erc725_rpcUrls}
      uniresolver_driver_did_erc725_etherscanApis: ${uniresolver_driver_did_erc725_etherscanApis}
    ports:
      - "8085:8080"
  driver-dns:
    image: universalresolver/driver-dns:latest
    environment:
      uniresolver_driver_dns_dnsServers: ${uniresolver_driver_dns_dnsServers}
    ports:
      - "8087:8080"
  jolocom-did-driver:
    image: jolocomgmbh/jolocom-did-driver:latest
    ports:
      - "8088:8080"
  hacera-did-driver:
    image: hacera/hacera-did-driver:latest
    ports:
      - "8089:8080"
  seraph-id-did-driver:
    image: swisscomblockchainag/seraph-id-did-driver:latest
    ports:
      - "8090:8080"
  driver-did-ccp:
    image: hello2mao/driver-did-ccp:latest
    ports:
      - "8091:8080"
  work-did-driver:
    image: didwork/work-did-driver:latest
    environment:
      uniresolver_driver_did_work_apikey: ${uniresolver_driver_did_work_apikey}
      uniresolver_driver_did_work_domain: ${uniresolver_driver_did_work_domain}
    ports:
      - "8092:8080"
  ontid-driver:
    image: ontio/ontid-driver:latest
    ports:
      - "8093:8080"
  kilt-did-driver:
    image: kiltprotocol/kilt-did-driver:1.0.1
    environment:
      uniresolver_driver_kilt_did_node: ${uniresolver_driver_kilt_did_node}
    ports:
      - "8094:8080"
  evan-did-driver:
    image: evannetwork/evan-did-driver:latest
    ports:
      - "8095:8080"
  uni-resolver-driver-did-echo:
    image: echoprotocol/uni-resolver-driver-did-echo:latest
    environment:
      uniresolver_driver_did_echo_mainnet_rpc_url: ${uniresolver_driver_did_echo_mainnet_rpc_url}
      uniresolver_driver_did_echo_testnet_rpc_url: ${uniresolver_driver_did_echo_testnet_rpc_url}
      uniresolver_driver_did_echo_devnet_rpc_url: ${uniresolver_driver_did_echo_devnet_rpc_url}
    ports:
      - "8096:8080"
  driver-did-factom:
    image: sphereon/driver-did-factom:latest
    ports:
      - "8097:8080"
  driver-did-key:
    image: universalresolver/driver-did-key:latest
    ports:
      - "8098:8080"
  dock-did-driver:
    image: docknetwork/dock-did-driver:latest
    ports:
      - "8099:8080"
  uni-resolver-did-v1-driver:
    image: veresone/uni-resolver-did-v1-driver:latest
    ports:
      - "8100:8080"
  driver-did-abt:
    image: arcblock/driver-did-abt:latest
    ports:
      - "8101:8080"
  driver-did-trustbloc:
    container_name: driver-did-trustbloc
    image: trustbloc/driver-did-trustbloc:0.1.3
    environment:
      DID_METHOD_HOST_URL: ${DID_METHOD_HOST_URL}
      DID_METHOD_TLS_SYSTEMCERTPOOL: ${DID_METHOD_TLS_SYSTEMCERTPOOL}
      DID_METHOD_MODE: ${DID_METHOD_MODE}
    ports:
      - "8102:8080"
    command: start
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"