apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{containerName}}
  namespace: uni-resolver-dev
  labels:
    app: {{containerName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{containerName}}
  template:
    metadata:
      labels:
        app: {{containerName}}
    spec:
      containers:
      - name: {{containerName}}
        image: {{containerTag}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "5m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: {{containerPort}}
        securityContext:
          capabilities:
            drop:
              - NET_RAW
---
apiVersion: v1
kind: Service
metadata:
  name: {{containerName}}
  namespace: uni-resolver-dev
spec:
  type: NodePort
  selector:
    app: {{containerName}}
  ports:
    - protocol: TCP
      port: {{containerPort}}
      targetPort: {{containerPort}}
