# Dockerfile

FROM debian:stretch
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apt-get -y update

RUN apt-get install -y --no-install-recommends openjdk-8-jdk maven && \
    apt-get clean

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH $JAVA_HOME/bin:$PATH

ADD . /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean install package -N -DskipTests
RUN cd /opt/uni-resolver-java/uni-resolver-core && mvn clean install package -N -DskipTests
RUN cd /opt/uni-resolver-java/driver && mvn clean install package -N -DskipTests
RUN cd /opt/uni-resolver-java/driver-did-btcr && mvn clean install package -N -DskipTests

# done

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8080

CMD ["/opt/uni-resolver-java/docker/run-driver-did-btcr.sh"]
