name: 'uni-resolver-get-driver-status'
description: 'Get driver status for Universal Resolver deployment'
inputs:
  host:
    description: 'Host of Uni-Resolver deployment'
    required: false
    default: https://dev.uniresolver.io
  config:
    description: 'Uni-Resolver configuration file'
    required: false
    default: /github/workspace/uni-resolver-web/src/main/resources/application.yml
  out:
    description: 'Folder location of driver-status-result-<timestamp> file'
    required: false
    default: /github/workspace/uni-resolver-web/driver-status-reports
  debug:
    description: 'Enhance logging'
    required: false
    default: false
  keep_result:
    description: 'Keep result file'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.config }}
    - ${{ inputs.out_folder }}
