openapi: 3.0.0
servers:
  - url: /1.0/
info:
  description: Universal Resolver
  version: "1.0.0"
  title: Universal Resolver
  contact:
    email: markus@danubetech.com
paths:
  /identifiers/{identifier}:
    get:
      summary: Resolve a DID.
      description:
        <p>This endpoint resolves a DID. As input it takes the DID, plus DID resolution
        <a href="https://www.w3.org/TR/did-core/#did-resolution-options">options</a>. The output is a DID
        document
        in one of the supported representations, plus metadata.</p>
        <p>See the <a href="https://w3c-ccg.github.io/did-resolution/">DID Resolution</a>
        specification for additional details.</p>
      operationId: resolve
      parameters:
        - in: path
          required: true
          name: identifier
          schema:
            type: string
          description: The DID to be resolved.
          examples:
            example1:
              value: did:indy:sovrin:builder:VbPQNHsvoLZdaNU7fTBeFx
              description: A DID using the `indy` method.
            example2:
              value: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
              description: A DID using the `ion` method.
            example3:
              value: did:ebsi:z25ZZFS7FweHsm9MX2Qvc6gc
              description: A DID using the `ebsi` method.
        - in: header
          required: false
          name: Accept
          schema:
            type: string
          description: The requested media type of the DID document representation or DID resolution result. See <a href="https://www.w3.org/TR/did-core/#representations">https://www.w3.org/TR/did-core/#representations</a> and <a href="https://w3c-ccg.github.io/did-resolution/#did-resolution-result">https://w3c-ccg.github.io/did-resolution/#did-resolution-result</a>.
          examples:
            application/did+json:
              value: application/json
              description: Media type of a DID document (JSON representation).
            application/did+ld+json:
              value: application/did+ld+json
              description: Media type of a DID document (JSON-LD representation).
            application/ld+json;profile="https://w3id.org/did-resolution":
              value: application/ld+json;profile="https://w3id.org/did-resolution"
              description: Media type of a DID resolution result (JSON-LD representation).
      responses:
        '200':
          description: successfully resolved!
          content:
            application/did+json:
              schema:
                type: object
                description: The DID document (JSON representation).
                example: {
                  "id": "did:indy:sovrin:WRfXPg8dantKVubE3HX8pw",
                  "verificationMethod": [
                    {
                      "id": "did:indy:sovrin:WRfXPg8dantKVubE3HX8pw#key-1",
                      "type": "Ed25519VerificationKey2018",
                      "publicKeyBase58": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
                    }
                  ]
                }
            application/did+ld+json:
              schema:
                type: object
                description: The DID document (JSON-LD representation).
                example: {
                  "@context": "https://www.w3.org/ns/did/v1",
                  "id": "did:indy:sovrin:WRfXPg8dantKVubE3HX8pw",
                  "verificationMethod": [
                    {
                      "id": "did:indy:sovrin:WRfXPg8dantKVubE3HX8pw#key-1",
                      "type": "Ed25519VerificationKey2018",
                      "publicKeyBase58": "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
                    }
                  ]
                }
            application/ld+json;profile="https://w3id.org/did-resolution":
              schema:
                $ref: '#/components/schemas/ResolutionResult'
        '400':
          description: invalid input!
        '410':
          description: successfully resolved (deactivated)!
          content:
            application/did+json:
              schema:
                type: object
                description: The deactivated DID document (JSON representation).
            application/did+ld+json:
              schema:
                type: object
                description: The deactivated DID document (JSON-LD representation).
            application/ld+json;profile="https://w3id.org/did-resolution":
              schema:
                $ref: '#/components/schemas/ResolutionResult'
        '500':
          description: error!
  /properties:
    get:
      summary: Returns a map of properties of the resolver.
      operationId: universalResolverGetProperties
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of properties.
  /methods:
    get:
      summary: Returns a list of supported DID methods.
      operationId: universalResolverGetMethods
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: array
                items:
                  type: string
                description: The list of supported DID methods.
                example: ["btcr","indy","v1","key"]
  /testIdentifiers:
    get:
      summary: Returns a list of test identifiers that can be resolved.
      operationId: universalResolverGetTestIdentifiers
      responses:
        '200':
          description: Success.
          content:
            application/did+json:
              schema:
                type: object
                description: A map of test identifiers, grouped by DID method.
                example: { "btcr": ["did:btcr:xz35-jznz-q9yu-ply", "did:btcr:xkrn-xz7q-qsye-28p"], "indy": ["did:indy:sovrin:WRfXPg8dantKVubE3HX8pw"] }
components:
  schemas:
    ResolutionResult:
      description: The DID resolution result.
      type: object
      additionalProperties: false
      properties:
        didDocument:
          type: object
        didResolutionMetadata:
          type: object
        didDocumentMetadata:
          type: object
