kubectl delete all --all -n uni-resolver
kubectl -n uni-resolver apply -f deployment-driver-did-btcr.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-sov.yaml 
kubectl -n uni-resolver apply -f deployment-uni-resolver-driver-did-uport.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-stack.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-erc725.yaml 
kubectl -n uni-resolver apply -f deployment-driver-dns.yaml 
kubectl -n uni-resolver apply -f deployment-jolocom-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-hacera-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-seraph-id-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-ccp.yaml 
kubectl -n uni-resolver apply -f deployment-work-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-ontid-driver.yaml 
kubectl -n uni-resolver apply -f deployment-kilt-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-evan-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-uni-resolver-driver-did-echo.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-factom.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-key.yaml 
kubectl -n uni-resolver apply -f deployment-dock-did-driver.yaml 
kubectl -n uni-resolver apply -f deployment-uni-resolver-did-v1-driver.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-abt.yaml 
kubectl -n uni-resolver apply -f deployment-driver-did-trustbloc.yaml 
kubectl -n uni-resolver apply -f deployment-uni-resolver-web.yaml 
kubectl -n uni-resolver apply -f deployment-uni-resolver-frontend.yaml 
