# Dockerfile for universalresolver/base-alpine

FROM ubuntu:18.04
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends openjdk-8-jdk-headless maven git && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV PATH $JAVA_HOME/bin:$PATH

# build dependencies

RUN cd /opt/ && git clone https://github.com/peacekeeper/did-common-java.git
RUN cd /opt/did-common-java/ && git checkout matrix-parameters && mvn clean install -DskipTests

# build driver

ADD . /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean install -N -DskipTests && \
    cd /opt/uni-resolver-java/uni-resolver-core && mvn install -N -DskipTests && \
    cd /opt/uni-resolver-java/driver && mvn install -N -DskipTests
