name: Docker release image

on:
  workflow_dispatch:

jobs:

  docker-release:
    uses: danubetech/workflows/.github/workflows/maven-triggered-docker-release.yml@main
    with:
      GLOBAL_IMAGE_NAME: universalresolver/uni-resolver-web
      GLOBAL_REPO_NAME: docker.io
      GLOBAL_FRAMEWORK: maven
      PATH_TO_DOCKERFILE: uni-resolver-web/docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
