name: Driver health check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  driver-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get driver status
        uses: ./ci/get-driver-status
        with:
          host: https://dev.uniresolver.io
          out_folder: /github/workspace/driver-status-reports
          keep_result: true
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run did-testsuite
        uses: ./ci/run-did-testsuite
        with:
          host: https://testsuite.uniresolver.io/test-suite-manager/generate-report
          driver_status_report: ${{ env.driver_status_report }}
          reports_folder: ${{ env.reports_folder }}
