name: Maven snapshot artifact

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/maven-danubetech-nexus username | MAVEN_USERNAME ;
            ci/data/gh-workflows/maven-danubetech-nexus password | MAVEN_PASSWORD ;
            ci/data/gh-workflows/deployment-status slack-webhook-url | SLACK_WEBHOOK_URL
      - name: Run maven deploy action
        uses: danubetech/github-action-maven-deploy@master
        with:
          server_id: danubetech-maven-snapshots
          path_to_pom: /github/workspace/
        env:
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        if: failure()
